---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать каталог товаров и подробную информацию о товаре
  - В каталоге и на странице товара должны отображаться название, рейтинг, цена без скидки и цена со скидкой
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать её содержимое
  - Пользователь должен иметь возможность переключить язык интерфейса
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
  - Пользователь должен иметь возможность оформить заказ с переходом на страницу оплаты
non-functional:
  - Сайт нужно разработать с учётом удобства использования и оптимизировать скорость работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию (адаптивная вёрстка)
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен выдерживать большое количество одновременного трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен быть доступен напрямую из сети Интернет, без использования VPN
implicit:
  - Приложение должно быть SPA (без перезагрузки страницы)
  - Каталог должен поддерживать постраничный вывод (пагинацию)
  - Пользователь должен иметь возможность удалять товары из корзины
  - Пользователь должен иметь возможность продолжить выбор товаров в каталоге после добавления/удаления товара в корзине
  - Пользователь должен иметь возможность оформить заказ с переходом на страницу оплаты
  - Корзина должна сохраняться в сессии браузера (session storage)
  - Значения цен и скидок должны отображаться корректно (валюта, формат, округление) и единообразно во всех местах
